version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/todo
    ports:
      - 9080:9080
      - 8080:8080
    command: sleep infinity

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - ./volume/dbdata:/var/lib/postgresql/data
