version: '3'

services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/todo:delegated
      - ../../_volume/gradle:/home/vscode/.gradle:delegated
      - ../../_volume/vscode-server:/home/vscode/.vscode-server:delegated
    ports:
      - 8080:8080
    command: sleep infinity

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - ../../_volume/dbdata:/var/lib/postgresql/data
